### ISSUE TITLE
For what rtsp-stream?

### ISSUE THREAD

**Issue by Globik** [tan-tan-kanarek/mediasoup-server#1]
As I know mediasoup does not support rtsp. 
And this is very interesting why are you using rtsp. Is this for outer ip camera streaming?

**Comment by tan-tan-kanarek** [comment]
I implemented the RTSP server myself, it's not for the WebRTC, it's for other tools to pull the stream over RTSP. In fact, using this RTSP server I pull the RTP packets using VLC or FFMPEG that are able to transcode the stream, to save it to file or to stream it on to RTMP media server.

**Comment by Globik** [comment]
Any plan to update to mediasoup 1.0.1?
Breaking changes in its api. I've tried your demo but unlucky. On serverside when creating peer. Peer should use method setCapabilities(). All that breaking the code.

**Comment by Globik** [comment]
Apropos, there is demo of mediasoup in action(online) but their code not easy understandable. Client side out of react.js and server side unknown protoo websocket.
https://demo.mediasoup.org

**Comment by tan-tan-kanarek** [comment]
Thanks, I'll check their demo when I have the time, until then you can use the old version as specified in the package.json.

**Comment by yarekc** [comment]
Looks promising...
Are you able to create a many2many solution using mediaSoup ?
I am looking for a freelancer. My skupe is : proxymis for futher details.

**Comment by tan-tan-kanarek** [comment]
I will try to upgrade the mediasoup to latest version and to give it a try.

**Comment by tan-tan-kanarek** [comment]
Upgraded to 1.2.2, many2many is supported now, also fixed bug for firefox.

**Comment by yarekc** [comment]
hi, thanks.
Is there a chance I can catch you on skype (or email) to explain you my needs (and hire your expertise)
yarekc at gmail dot com
Regards
