### ISSUE TITLE
Getting issue for recording when adding 2 or more users in meeting/session

### ISSUE THREAD

**Issue by krishnapsarthi** [tan-tan-kanarek/mediasoup-server#25]
Hello @tan-tan-kanarek ,

Using media soup-server am able to record stream when single user in meeting, as soon as second peer joins the meeting am getting error in log file:- 
nal_unit_type: 1, nal_ref_idc: 3
[h264 @ 0x555721a3efa0] non-existing PPS 1 referenced
[h264 @ 0x555721a3efa0] decode_slice_header error
[h264 @ 0x555721a3efa0] no frame!

I think Rtsp not able process multiple stream at same time.

do you have any idea or any suggestion?

Thanks

**Comment by tan-tan-kanarek** [comment]
Sorry, I'm not working on this project at the moment, I hope to find time to get back to it soon.

**Comment by krishnapsarthi** [comment]
@tan-tan-kanarek: Thanks for replying, just to rephrase my issue, it seems like adding another peer in a meeting session is causing the ffmpeg to call Teardown like

RTSP Request [TEARDOWN] rtsp://192.168.40.98:5001/62048934.sdp
Streamer [62048934] closed

This is corrupting the recorded the file (flv in my case) since I am publishing to a remote RTMP server.

Hope you get some time review the issue, I will continue to dig more

Thanks,

**Comment by tan-tan-kanarek** [comment]
This code is using old version of mediasoup and therefore it won't be maintained and I recommend to use it as reference only and not as is.
