### ISSUE TITLE
cannot get example to work

### ISSUE THREAD

**Issue by fozzle** [tan-tan-kanarek/mediasoup-server#9]
Hi,

Thanks for all your hard work on this wonderful project. Recording and rtmp forwarding are important features to me and your work will save me a lot of stumbling in the dark.

I was having problems getting the example to work on my local machine. Here's a typical log:

https://gist.github.com/fozzle/0a4bfa9899de22ce5e74b601b3497098

Also, I cannot open the rtsp source with VLC, it gives "codec not found errors" but then sometimes will start showing the stream but without audio. Ha.

Funny enough, I've gotten RTMP forwarding to a remote media server (Wowza) to work just fine, but the audio is extremely desynced.

I wanted to see if I could debug the desync but since I can't get the example to run it's hard to isolate.

Am I missing something?

**Comment by tan-tan-kanarek** [comment]
What version of this project do you use?
Of course I recommend to use the latest, but you should know that 1.0.1 is the first stable version.

**Comment by fozzle** [comment]
I was able to make some recordings this morning with 1.0.4. Didn't make any changes so unsure why it wouldn't have worked before. Will go ahead and close this for now.
